### ISSUE TITLE
Error while trying to send embed message

### ISSUE THREAD

**Issue by HysteriaMC** [greatplainsmodding/DBM-Dashboard#17] opened 2020-05-09 23:53 UTC
Hi, i got this error while trying to send an embed message https://tao-is-developing.online/ss/ssqk53.png.

All node modules are installed as requested on the tutorial. but still doesn't work.

**Comment by Thaliruth** [comment] 2020-05-13 08:13
Can I confirm, the same problem

**Comment by Thaliruth** [comment] 2020-05-13 09:06
I have installed the Node Module Discord.JS again because I was advised to do so. Now I get the following message that an empty Ebemd seems to be sent

```
(node:27451) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send an empty message
    at /home/thaliruth/gollum/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15
    at /home/thaliruth/gollum/node_modules/snekfetch/src/index.js:215:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:27451) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

**Comment by greatplainsmodding** [comment] 2020-05-13 09:08
Whatever the issue is, it is fixed in the latest version that will be released soon.

**Closed by greatplainsmodding** 2020-05-13 09:08 UTC
